/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include <string.h>
#include "../Driver/Inc/stm32f446xx.h"
#include "../Bsp/MPU_gy_521.h"

extern void initialise_monitor_handles(void);

int main(void)
{
	initialise_monitor_handles();
	printf("Semi hosting: activated\n");
	MPU_Config_t gy_521;
	MPU_Data_t MPU;
	gy_521.MCU_addr_config = 0x61;
	gy_521.scl_port_config = pGPIOB;
	gy_521.scl_pin_config = GPIO_PIN_NO_6 ;
	gy_521.sda_port_config = pGPIOB;
	gy_521.sda_pin_config = GPIO_PIN_NO_7;
	gy_521.alt_mode = 4;
	gy_521.accel_config = 0x00;
	gy_521.gyro_config = 0x00;
	gy_521.pI2Cx = pI2C1;

	MPU_i2c_inits(&gy_521);
	 while (1)
	 {
		MPU = MPU_Data_read();
		printf("MPU Data:\n");
		printf("Acceleration X: %d\n", MPU.accel_x);
		printf("Acceleration Y: %d\n", MPU.accel_y);
		printf("Acceleration Z: %d\n", MPU.accel_z);
		printf("Gyroscope X: %d\n", MPU.gyro_x);
		printf("Gyroscope Y: %d\n", MPU.gyro_y);
		printf("Gyroscope Z: %d\n", MPU.gyro_z);
		printf("Temperature: %f.%02d C\n", MPU.temperature / 100, ((int)MPU.temperature % 100)); // @suppress("Float formatting support")
	 }

}

